### ISSUE TITLE
PODAM does not populate fields when BeanValidation annotations present

### ISSUE THREAD

**Issue by ignaciolarranaga** [devopsfolks/podam#189]
For example, a POJO with an string an a validation NotEmpty is not populated.
A short field with a @Min annotation is neither populated.

**Comment by mtedone** [comment]
Podam does not honour all Hibernate validation annotations. I'm flagging this for future consideration unless, of course, you want to implement the remaining changes.

**Comment by daivanov** [comment]
In general Podam cannot support all imaginable validation annotations. If you face such need you always can extend DataProviderStrategy [with adding custom AttributeStrategy](https://devopsfolks.github.io/podam/apidocs/uk/co/jemos/podam/api/RandomDataProviderStrategy.html#addOrReplaceAttributeStrategy-java.lang.Class-java.lang.Class-) implementing what you need.

**Comment by maxdidato** [comment]
Hello,  I am facing the same problem. What I think @ignaciolarranaga was saying is that every time podam find a org.hibernate.validator.constraints annotation (or maybe any other type of annotation) it just ignore the attribute. 
So, for example, the following class

```
public class Test {

    @PodamStringValue(length = 3)
    @Length(min = 3, max = 3)
    String varA;

    @PodamStringValue(length = 3)
    String varB;
}
```

Will result in generating an object with only varB populated. varA will be ignored I think because the Hibernate annotation clash

**Comment by daivanov** [comment]
Can you use javax.validation.constraints.Size instead of I guess org.hibernate.validator.constraints.Length?

**Comment by maxdidato** [comment]
Hello. I think I could try but what I would like to understand is this part of code

```
 if (annotation.annotationType().getAnnotation(Constraint.class) != null) {
                if (annotation instanceof NotNull ||
                        annotation.annotationType().getName().equals("org.hibernate.validator.constraints.NotEmpty")) {
					/* We don't need to do anything for NotNull constraint */
                    iter.remove();
                } else if (!NotNull.class.getPackage().equals(annotationClass.getPackage())) {
                    LOG.warn("Please, register AttributeStratergy for custom "
                            + "constraint {}, in DataProviderStrategy! Value "
                            + "will be left to null", annotation);
                }
            } else {
                iter.remove();
            }
```

It seems that any Constraint annotation used on attribute level will force the user to provide a specific AttributeStrategy or the attribute itself would be left empty. Is there a reason for that? As podam doesn't support any validation annotation (apart for Email as I could see), would not make sense removing the else if branch completely?

I was preparing a pull request with a failing test and I could easily fix the issue removing the else if branch. But I could not figure out the reason for it

**Comment by daivanov** [comment]
Hi!

Podam supports all constraint annotations from package [javax.validation.constraints](http://docs.oracle.com/javaee/6/api/javax/validation/constraints/package-summary.html) with notable exception of Pattern. Also, as you can see from the snippet, Podam supports `org.hibernate.validator.constraints.NotEmpty`, which appears to be Podam's default strategy.

What Podam does not support, is custom Hibernate constraints from package [org.hibernate.validator.constraints](https://docs.jboss.org/hibernate/validator-backup/5.1/api/org/hibernate/validator/constraints/package-summary.html). Including `org.hibernate.validator.constraints.Email`.

So, if you want to limit size of a string, you have two options:
1. Use `javax.validation.constraints.Size`
2. Create custom `AttributeStrategy` for `org.hibernate.validator.constraints.Length`

What is valid here is that Podam selects only one constraint, if multiple constraints are attached to a field. Could you please file a bug for this or I will do it later myself.

**Comment by maxdidato** [comment]
Thanks for the explanation. 
In my case my pojo contains custom Hibernate validation tags but I don't want them to be considered by podam. That is why on top of the Hibernate annotation I have added a podam annotation, to instruct the generator on how I want my field populated. Since Hibernate validations are not supported why don't you ignore them completely Rather than applying the BeanValidation strategy?

**Comment by daivanov** [comment]
The reason for this is that `org.hibernate.validator.HibernateValidator` or whatever non JavaEE validator will report errors for default stuff injected by Podam, but null values are fine, unless there is also `NotNull/NotEmpty` annotation.

**Comment by maxdidato** [comment]
I understand. Thanks for making it clear

**Comment by daivanov** [comment]
In general this is rather controversial topic as there are people, who do not want hibernate-validator as Podam dependency and there are people, who want Hibernate constraint annotations support.

**Comment by maxdidato** [comment]
In order to raise an error during the generation of random values,Podam
should trigger the validation engine of Hibernate, is that right?

**Comment by daivanov** [comment]
Something will call the validation engine, not Podam. Please, file an issue regarding multiple annotations on the same field.

**Comment by daivanov** [comment]
I re-used Issue #205 to report this bug. Do you want to make a PR fixing it or should I do it?

**Comment by maxdidato** [comment]
I can do it if you want
