### ISSUE TITLE
Podam fails to select right annotation in case a field has multiple annotations

### ISSUE THREAD

**Issue by Mdoniseter** [devopsfolks/podam#205]
A sample POJO

    public class Test {

        @PodamStringValue(length = 3)
        @Length(min = 3, max = 3)
        String field;
    }

**Comment by maxdidato** [comment]
So, basically, if a Podam annotation is present on a attribute/method, all the other annotations should be ignored.

**Comment by daivanov** [comment]
Yes, I think this is the best approach.

**Comment by maxdidato** [comment]
What is the best way to contribute? I cannot see any information on the ReadME. You want the pull request created against develop?

**Comment by daivanov** [comment]
Yes, develop is the development branch.  But patch with 20 changed files with 1,983 additions and 1,979 deletions has very little chance of merging ;)

**Comment by daivanov** [comment]
Fixed in Podam 7.0.5.

**Comment by daivanov** [comment]
You can try Podam's [snapshot](https://oss.sonatype.org/content/repositories/snapshots/uk/co/jemos/podam/podam/7.0.5-SNAPSHOT/podam-7.0.5-20170115.122125-1.jar).
