### ISSUE TITLE
lots of unwanted COMPILE dependencies (spring, spring integration, hibernate validator)

### ISSUE THREAD

**Issue by fbus** [devopsfolks/podam#210]
Since 5.3.x the pom as lots of dependencies.
I don't want to pull all those dependencies juste to generate some random beans.
At least add them as optional dependencies (  <optional>true</optional> )
Also, please note that for *compilation* hibernate validator should not be needed (it's the implementation of the validation API which is already here as  a dependency)

**Comment by daivanov** [comment]
I absolutely second this.

**Comment by daivanov** [comment]
Fixed in Podam 6.0.4
