### ISSUE TITLE
All values of a class setted to null

### ISSUE THREAD

**Issue by pacellig** [devopsfolks/podam#211]
Trying to use the library in order to create random instances of unknown object ( which type is known at runtime ), all the values inside such a class are setted to null.
Might it be that these fields are private, and so they are not seen/changed by the library?

i.e. Trying to create a random instance of originalObject

```
PodamFactory factory = new PodamFactoryImpl();
Object x = factory.manufacturePojo(originalObject.getClass());
```

all fields for x are null.

**Comment by mtedone** [comment]
You need to use the manufacturePojoWithFullData method. 

Regards,
M.

**Comment by daivanov** [comment]
> Might it be that these fields are private, and so they are not seen/changed by the library?
There could be million reasons for that. Could you please show the code of your POJO class?

**Comment by pacellig** [comment]
I haven't the code for the class, since I am trying to generate random instances of objects which type is only known at runtime, through reflection.
I tried with ManufacturePojoWithFullData but doesn't seem to work as well.

**Comment by daivanov** [comment]
> I haven't the code for the class, since I am trying to generate random instances of objects which type is only known at runtime, through reflection.

Without knowing, which class isn't populated it's impossible to say anything about this issue. Name the problematic class or present a Podam log, which should contain enough information for fixing this issue.

**Comment by pacellig** [comment]
I cannot share my POJO class since I am trying to randomize objects which type is only known at runtime. Thank you for your help.

**Comment by daivanov** [comment]
Even you use random objects at runtime, they are still specific objects at each specific execution, so you can print class name into the log and Podam logs data regarding its instantiation as well.
