### ISSUE TITLE
ManufaturePOJO to String class on Java8

### ISSUE THREAD

**Issue by sdfsfas** [devopsfolks/podam#213]
Hi,
If you run this code with java8, the manufature will gather the String constructor(String(byte[] bytes, int offset, int length), so when generating radom int you will get outOfBounds.

    import org.junit.Test;
    import uk.co.jemos.podam.api.PodamFactory;
    import uk.co.jemos.podam.api.PodamFactoryImpl;

    public class PodamProof {
        @Test
        public void testStringJava8(){
            PodamFactory factory = new PodamFactoryImpl();
            String pojo = factory.manufacturePojo(String.class);
            System.out.print(pojo);
       }     
      }

Kind Regards

**Comment by daivanov** [comment]
There is already [a test](https://github.com/daivanov/joinmo/blob/master/src/test/java/uk/co/jemos/podam/test/unit/PodamMockerUnitTest.java#L740) for this and it doesn't fail.

**Comment by daivanov** [comment]
I have to admit that this plain String instantiation is not working in 6.0.3.RELEASE

**Comment by daivanov** [comment]
Fixed in [6.0.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/uk/co/jemos/podam/podam/6.0.4-SNAPSHOT/)
