### ISSUE TITLE
Add support for setter methods not starting with set

### ISSUE THREAD

**Issue by krzysiekbr** [devopsfolks/podam#217]
Most of classes I'm using in my project have setters starting with "with" keyword and returning "this". For now, if I understand it correctly, it's not possible for me to use Podam because it searches methods starting by "set" keyword and returning void (as per PodamUtils.java)

Is it possible to make Podam search for both of these method prefixes ("set" and "with") or make this prefix configurable?

**Comment by daivanov** [comment]
Yes, this is possible. You can implement your own version of _ClassInfoStrategy_ or extend _AbstractClassInfoStrategy_ overriding _ClassInfoStrategy.getClassInfo(Class<?> pojoClass)_ and feed this strategy to a Podam factory.

**Comment by daivanov** [comment]
7.0.1 snapshot available from [here](https://oss.sonatype.org/content/repositories/snapshots/uk/co/jemos/podam/podam/7.0.1-SNAPSHOT/podam-7.0.1-20161025.200315-1.jar).

**Comment by krzysiekbr** [comment]
Thanks for quick reaction. I wrote my own strategy implementation and it works like a charm.

**Comment by daivanov** [comment]
Thank you for pointing this out. I've changed AbstractClassInfoStrategy implementation so it's a bit easier to override:

        ClassInfoStrategy classInfoStrategy = new AbstractClassInfoStrategy() {
            @Override
            protected Pattern getGetterPattern() {
                return Pattern.compile("^whatIs");
            }

            @Override
            protected Pattern getSetterPattern() {
                return Pattern.compile("^with");
            }
        };
        PodamFactory factory = new PodamFactoryImpl();
        factory.setClassStrategy(classInfoStrategy);

**Comment by krzysiekbr** [comment]
That makes everything much easier for me, thanks. When these changes can be released?

**Comment by daivanov** [comment]
Now Podam 7.0.1 is released, it will appear at some point at Maven repository.
