### ISSUE TITLE
Expose constructor index of parent pojo to TypeManufacturer

### ISSUE THREAD

**Issue by devshorts** [devopsfolks/podam#221]
I'm working on building a set of scala friendly type manufacturers and so far things work great. However, scala has crazy stuff which allow (through a bunch of weird indirection) primitives as the generic parameter of a container.  For example:

```Option[Int]```

There are ways to determine the inner argument type by parsing the scala bytecode (this is what finatra jackson does), and thats fine. However, I can only find this information from the parent classes constructor arguments.  This means that whenever I'm constructing my type, I need to inspect the containers arguments.  But, since I don't have the currently constructing _index_ I don't know which constructor parameter to look at.

For example:

```
case class OptionHolder(option1: Option[Long], option2: Option[Int])
```

I can determine both `Long` and `Int` if I know that the constructor parameter being constructed is the first or second. I can see see in `getParameterValuesForConstructor` that we do have the index. Is it possible to expose this on the attributeMetadata class?

**Comment by daivanov** [comment]
Yes, this has been a problem for a long time, but unfortunately Java doesn't allow to find a constructor index. But I think Podam can be passing constructor definition with an index of a parameter.

**Comment by daivanov** [comment]
A snapshot is available [here](https://oss.sonatype.org/content/repositories/snapshots/uk/co/jemos/podam/podam/7.0.2-SNAPSHOT/podam-7.0.2-20161104.235644-2.jar).

**Comment by devshorts** [comment]
Awesome, thanks!

**Comment by daivanov** [comment]
So what's your opinion about the change?
