### ISSUE TITLE
Manufacturing of nested generic type properties 

### ISSUE THREAD

**Issue by opeled** [devopsfolks/podam#225]
I have the following object hierarchy:

`public class A {
private B<String> b;
}`

`public class B<T> {
private List<C<T>> values;
`

`public class C<T> {
private T value;
}`

Trying to manufacture an A object with data using:
`new PodamFactoryImpl().manufacturePojo(A.class)` 

throws the following exception:
`java.lang.IllegalStateException: com.C is missing generic type arguments, expected [T] found [T]`

needless to say this works:
`new PodamFactoryImpl().manufacturePojoWithFullData(C.class, String.class)`

**Comment by opeled** [comment]
This is not exactly the same, as in the test reference, the `GenericListPojo` class is generic.
In my example the `A` class is not generic, however it contains a generic proeprty.

**Comment by daivanov** [comment]
Your class B is also generic. And error is the same, but I guess you are using some older version of Podam:

uk.co.jemos.podam.exceptions.PodamMockeryException: An exception occurred while resolving the collection
	at uk.co.jemos.podam.test.unit.pdm45.Pdm45UnitTest.testGenericListPojoManufacture(Pdm45UnitTest.java:45)
Caused by: java.lang.IllegalArgumentException: uk.co.jemos.podam.test.dto.pdm45.GenericPojo is missing generic type arguments, expected [F, S], provided [F, S]
	at uk.co.jemos.podam.test.unit.pdm45.Pdm45UnitTest.testGenericListPojoManufacture(Pdm45UnitTest.java:45)

**Comment by daivanov** [comment]
Please, give it a try with [Podam 7.0.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/uk/co/jemos/podam/podam/7.0.4-SNAPSHOT/podam-7.0.4-20161221.010316-1.jar).

**Comment by opeled** [comment]
Issue solved.
Can you please release and upload to mvn repository ?

**Comment by daivanov** [comment]
Now it should appear at some point in Maven. Thank you for reporting this issue.
