### ISSUE TITLE
pass actual annotation to an AttributeStrategy to allow customization

### ISSUE THREAD

**Issue by NBau** [devopsfolks/podam#237]
Since the generic case for supporting @Pattern as described in #218 will probably not be available very soon, a temporary enhancement could be to support providing custom manufacturers for specific patterns.
Right now, I cannot see an easy way to provide such a manufacturer since, e.g. the AttributeStrategy does not get passed the instance of the annotation in the getValue method.

**Comment by daivanov** [comment]
And why do we have two issues for the same problem?

**Comment by NBau** [comment]
Sorry, I was not sure how to do it differently. My idea was, instead of trying to solve the issue in #218 (I.e. Have a general way of supporting all patterns), just provide a way to register individual manufacturers for different patterns. This way, someone who wants to use the library but has some particular pattern annotation can hand-craft a specific manufacturer just for this case. Just like a custom type manufacturer. Unfortunately, this is not possible right now.

**Comment by daivanov** [comment]
Some improvements to the issue was released in Podam 7.0.5.

**Comment by dedece35** [comment]
As @daivanov said and with last release of Podam (7.1.0.RELEASE), I tested and succedded to customize my POJOs containing @Pattern annotation.
I did this with a Strategy like in Tests written by @daivanov  in commit https://github.com/daivanov/joinmo/commit/79be6f88d167cfcd20bad8e4b52533b90ac19bdd 
I think @daivanov you can close this issue.

**Comment by daivanov** [comment]
Yes, I assume this was about custom annotation handlers. But for generic pattern support with some library we have Issue #218.
