### ISSUE TITLE
Attribute with @Size(max = number) is not being considered

### ISSUE THREAD

**Issue by hfcipriano** [devopsfolks/podam#243]
Sorry for my probally ignorance. But I have the follow class in my project:

```
class A {
    @Size(max = 4)
    String s;

    get set...
}
```

and

```
PodamFactory podam = new PodamFactoryImpl();
A  test = podam.manufacturePojo(A.class);
```

The attribute s of the test variable was filled with a string of size 10.

What is possibly wrong?

**Comment by daivanov** [comment]
Hi,

What is @Size annotation class name?

BR, Daniil

**Comment by hfcipriano** [comment]
Sorry for my bad... I was using 5.3.2 version.
When i updated to 7.0.5 works beautiful.

**Comment by daivanov** [comment]
Ok, good that the problem solved.
