### ISSUE TITLE
Exclude some attributes

### ISSUE THREAD

**Issue by muhammed-sayadi** [devopsfolks/podam#256]
To avoid circular filling (and eventually a StackOverflow error), or for any other reason, it would be helpful to have the ability to exclude some attributes from being filled.

A common scenario in POJOs modeling tables in a relational database is some classes will reference each other in a ManyToMany relationship:
```
public ClassA {
   // Annotations for many to many relationship
   ClassB b;
}
```

```
public ClassB {
   // Annotations for many to many relationship
   ClassA a;
}
```

**Comment by daivanov** [comment]
You cannot have StackOverflow error as Podam will stop after 3 levels of objects are filled.
There are several ways to do what you want, but probably the best one consist of overriding boolean [ClassAttributeApprover.approve(ClassAttribute attribute)](https://devopsfolks.github.io/podam/apidocs/uk/co/jemos/podam/api/AbstractClassInfoStrategy.html#approve-uk.co.jemos.podam.api.ClassAttribute-) in `DefaultClassInfoStrategy` (or whatever `ClassInfoStrategy` you are using).

**Comment by daivanov** [comment]
Closing this as this is not an issue.
